# Generated by Django 5.1 on 2024-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
